baseURL = 'https://lciprian.github.io/'
languageCode = 'en-us'
title = 'Ciprian Lazar'
themesDir = 'themes'
theme = 'almeida-cv'

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#3f6592"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#3f6592"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#3f6592"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false